// tailwind.config.ts — MYND (unire al config esistente)
import type { Config } from "tailwindcss";
export default {
  darkMode: ["class", '[data-theme="dark"]'],
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "brand": "var(--brand)",
        "brand-ring": "var(--brand-ring)",
        "on-brand": "var(--on-brand)",
        "steel": "var(--steel)",
        "accent": "var(--accent)",
        "bg": "var(--bg)",
        "surface": "var(--surface)",
        "border": "var(--border)",
        "text": "var(--text)",
        "text-muted": "var(--text-muted)",
        "text-subtle": "var(--text-subtle)",
        "success": "var(--success)",
        "warning": "var(--warning)",
        "danger": "var(--danger)",
        "area-scuola": "var(--area-scuola)",
        "area-studio": "var(--area-studio)",
        "area-sport": "var(--area-sport)",
        "area-progetto": "var(--area-progetto)",
        "area-recupero": "var(--area-recupero)",
        "area-vita": "var(--area-vita)",
        "area-viaggio": "var(--area-viaggio)",
        "area-pasto": "var(--area-pasto)",
        "area-sonno": "var(--area-sonno)",
        "area-extra": "var(--area-extra)",
      },
      fontFamily: { sans: ["-apple-system","BlinkMacSystemFont","SF Pro Text","SF Pro Display","system-ui","Segoe UI","Roboto","sans-serif"] },
      fontSize: {
        display: ["52px", { lineHeight: "1", letterSpacing: "-0.05em", fontWeight: "700" }],
        h1: ["44px", { lineHeight: "1", letterSpacing: "-0.045em", fontWeight: "700" }],
        h2: ["34px", { lineHeight: "1.1", letterSpacing: "-0.035em", fontWeight: "700" }],
        h3: ["22px", { lineHeight: "1.25", letterSpacing: "-0.02em", fontWeight: "600" }],
        body: ["17px", { lineHeight: "1.5" }],
        small: ["15px", { lineHeight: "1.45" }],
        caption: ["13px", { lineHeight: "1.4" }],
        label: ["12px", { lineHeight: "1.3", letterSpacing: "0.08em", fontWeight: "500" }],
        num: ["76px", { lineHeight: "0.9", letterSpacing: "-0.04em", fontWeight: "300" }],
      },
      borderRadius: { sm: "8px", md: "16px", lg: "18px", xl: "28px", "2xl": "40px" },
      boxShadow: { spec: "var(--shadow-spec)", float: "var(--shadow-float)", lens: "var(--shadow-lens)", glow: "var(--glow-brand)", focus: "var(--focus-ring)" },
      backgroundImage: { "btn-primary": "var(--btn-primary)", "glass-hero": "var(--glass-hero)", steel: "var(--steel-gradient)", "icon-metal": "var(--icon-metal)", ambient: "var(--ambient)" },
      transitionDuration: { fast: "150ms", base: "250ms", slow: "600ms" },
      transitionTimingFunction: { out: "cubic-bezier(.2,.8,.2,1)", spring: "cubic-bezier(.3,1.3,.5,1)" },
    },
  },
} satisfies Config;
